<?php

/**
 * @file
 * Contains startrek.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function startrek_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the startrek module.
    case 'help.page.startrek':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('To boldly go where no man has gone before!') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_user_login().
 */
function startrek_user_login($account) {
  if ($account->hasPermission('onboard enterprise')) {
    \Drupal::service('startrek.enterprise.message')->setLoginMessage();
  }
}

/**
 * Implements hook_user_logout().
 */
function startrek_user_logout($account) {
  // drupal_set_message('User logout');.
}

/**
 * Implements hook_theme().
 */
function startrek_theme() {
  return [
    'message' => [
      'variables' => ['image' => NULL, 'message' => [], 'attributes' => []],
    ],
  ];
}
